DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user
(
  id BINARY(16) NOT NULL PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(500) NOT NULL,
  email VARCHAR(60),
  type VARCHAR(60)
);